"""Assemble the self-contained modeling file the Hub needs.

`transformers` loads remote code by copying the .py files a module imports --
but only FLAT relative imports. `from .src.model.moe_transformer import AbhiMoE`
is flattened to a filename, and loading dies on:

    FileNotFoundError: .../src.model.moe_transformer.py

So the Hub copy has to be one file. Rather than duplicate the model by hand and
let the two drift, this concatenates src/model/*.py in dependency order and
strips the intra-package imports. src/ stays the single source of truth; run
this again after changing it.
"""

import os
import re

# Dependency order: every name must be defined before it is used.
PARTS = ["norm", "rope", "mla", "moe", "moe_transformer"]

HEADER = '''"""Sutra-1.3B — MoE + Multi-head Latent Attention, in one file.

GENERATED by deploy/build_hf_module.py from src/model/. Do not edit here; edit
src/model/ and regenerate, or the Hub copy silently drifts from the trained
architecture.

Loads with:

    from transformers import AutoModelForCausalLM
    m = AutoModelForCausalLM.from_pretrained(
        "Abhisingh-18/Sutra-1.3B-Chat", trust_remote_code=True)
"""

import math
from dataclasses import dataclass

import torch
import torch.nn as nn
import torch.nn.functional as F
from transformers import PreTrainedModel
from transformers.modeling_outputs import CausalLMOutputWithPast

from .configuration_sutra import SutraConfig

'''

# Lines that must not survive the merge: the imports now in the header, and the
# intra-package imports whose targets are being inlined below them.
DROP = re.compile(
    r"^\s*(?:import\s+(?:math|json|torch)(?:\.\S+)?(?:\s+as\s+\w+)?\s*$"
    r"|import\s+torch\.nn(?:\.functional)?\s+as\s+\w+\s*$"
    r"|from\s+\.\w+\s+import\s"
    r"|from\s+dataclasses\s+import\s"
    r"|from\s+typing\s+import\s)")

WRAPPER = '''

# ---------------------------------------------------------------------------
# transformers wrapper
# ---------------------------------------------------------------------------


def _to_dataclass(config):
    fields = MoEModelConfig.__dataclass_fields__
    return MoEModelConfig(**{k: getattr(config, k)
                             for k in fields if hasattr(config, k)})


class SutraForCausalLM(PreTrainedModel):
    """The published safetensors was written by AbhiMoE, so its keys are
    `embed.*`, `blocks.*`, `final_norm.*`, `lm_head.*` with no prefix. Holding
    the core as `self.model` would look for `model.embed.*`, find nothing, and
    load a randomly initialised network WITHOUT raising -- so the core's
    children are adopted here and the published names are kept exactly.
    """

    config_class = SutraConfig
    _no_split_modules = ["MoEBlock"]
    _tied_weights_keys = []
    supports_gradient_checkpointing = True

    def __init__(self, config):
        super().__init__(config)
        core = AbhiMoE(_to_dataclass(config))
        self.cfg = core.cfg
        for name, child in core.named_children():
            setattr(self, name, child)
        # The RoPE table is deliberately NOT a buffer here. transformers builds
        # the model on the meta device and then materialises it from the
        # checkpoint; a non-persistent buffer is in the checkpoint under
        # neither name, so it survives that trip as uninitialised memory. The
        # values came back as 3.8e+22 and -5.9e12 -- and with rope_cos and
        # rope_sin identical, which no real table can be. Nothing raised:
        # every parameter was finite, every weight loaded, and the logits were
        # NaN. Built on demand instead, from config, where meta device cannot
        # reach it.
        self._rope = None
        # Required of every PreTrainedModel subclass. Without it the weights
        # still load -- all 2383 of them -- and from_pretrained then dies in
        # its own finalisation on bookkeeping post_init sets up.
        self.post_init()

    # transformers builds its own DynamicCache before calling generate, and
    # that machinery assumes a standard attention layout. This model caches a
    # 288-wide MLA latent per layer, not per-head K and V, so its cache is a
    # plain list of per-layer tuples that forward() manages itself. Returning
    # None here leaves it alone.
    def _prepare_cache_for_generation(self, *args, **kwargs):
        return None

    def _rope_tables(self, device):
        if self._rope is None or self._rope[0].device != device:
            cos, sin = build_rope_cache(self.cfg.qk_rope_head_dim,
                                        self.cfg.max_seq_len,
                                        self.cfg.rope_theta)
            self._rope = (cos.to(device), sin.to(device))
        return self._rope

    def get_input_embeddings(self):
        return self.embed

    def set_input_embeddings(self, value):
        self.embed = value

    def get_output_embeddings(self):
        return self.lm_head

    def forward(self, input_ids=None, attention_mask=None,
                past_key_values=None, labels=None, use_cache=True,
                return_dict=True, **kwargs):
        # A block only BUILDS a cache when it is handed one -- passing None
        # makes it return None, so seeding with plain None gives a list of
        # Nones on step two and generation dies indexing it. The convention
        # the model was written to is a list of (None, None) pairs.
        if past_key_values is None and use_cache:
            past_key_values = [(None, None)] * len(self.blocks)

        offset = 0
        if past_key_values is not None and past_key_values[0][0] is not None:
            # Every layer caches the same number of positions, so layer 0
            # carries the length for all of them.
            offset = past_key_values[0][0].shape[-2]

        x = self.embed(input_ids)
        cos, sin = self._rope_tables(x.device)
        new_caches = [] if past_key_values is not None else None

        for i, block in enumerate(self.blocks):
            cache = past_key_values[i] if past_key_values is not None else None
            x, c = block(x, cos, sin, cache, offset)
            if new_caches is not None:
                new_caches.append(c)

        x = self.final_norm(x)
        logits = self.lm_head(x).float()

        loss = None
        if labels is not None:
            loss = F.cross_entropy(
                logits[:, :-1].reshape(-1, logits.size(-1)),
                labels[:, 1:].reshape(-1), ignore_index=-100)

        return CausalLMOutputWithPast(
            loss=loss, logits=logits, past_key_values=new_caches)

    def prepare_inputs_for_generation(self, input_ids, past_key_values=None,
                                      **kwargs):
        if past_key_values:
            # Only the newest token needs a forward pass; the rest is cached.
            input_ids = input_ids[:, -1:]
        return {"input_ids": input_ids, "past_key_values": past_key_values,
                "use_cache": kwargs.get("use_cache", True)}


__all__ = ["SutraForCausalLM", "SutraConfig", "AbhiMoE", "MoEModelConfig"]
'''


def build(src_dir="src/model"):
    out = [HEADER]

    # The config dataclass, minus the json helpers that need `import json`.
    cfg_src = open(os.path.join(src_dir, "moe_config.py")).read()
    start = cfg_src.index("@dataclass")
    end = cfg_src.index("MOE_1B = ")
    body = "\n".join(l for l in cfg_src[start:end].splitlines()
                     if not DROP.match(l))
    # to_json/from_json read and write files; nothing on the Hub calls them.
    body = re.split(r"\n    def to_json", body)[0]
    out.append(body.rstrip() + "\n\n")

    for name in PARTS:
        text = open(os.path.join(src_dir, f"{name}.py")).read()
        # Drop the module docstring: five of them stacked reads as noise.
        text = re.sub(r'\A\s*""".*?"""\s*', "", text, flags=re.S)
        kept = [l for l in text.splitlines() if not DROP.match(l)]
        out.append(f"\n# ---- from src/model/{name}.py "
                   + "-" * max(0, 48 - len(name)) + "\n")
        out.append("\n".join(kept).strip() + "\n")

    out.append(WRAPPER)
    return "".join(out)


if __name__ == "__main__":
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    a = ap.parse_args()
    code = build()
    with open(a.out, "w") as f:
        f.write(code)
    compile(code, a.out, "exec")     # fail here, not on someone's machine
    print(f"wrote {a.out} ({len(code.splitlines())} lines)")
